export const REQUEST_ACTIONS = {
    REQUEST_IDLE: "REQUEST_IDLE",
    REQUEST_PENDING: "REQUEST_PENDING",
    REQUEST_LOADING: "REQUEST_LOADING",
    REQUEST_SUCCESS: "REQUEST_SUCCESS",
    REQUEST_ERROR: "REQUEST_ERROR",
}
